//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPvpApplication {
    
    public partial class TestPage {
        protected System.Web.UI.WebControls.Label UserLabel;
        protected System.Web.UI.WebControls.CheckBox AuthenticatedCheckBox;
        protected System.Web.UI.WebControls.Label NameLabel;
        protected System.Web.UI.WebControls.TextBox NameField;
        protected System.Web.UI.WebControls.Label ValueLabel;
        protected System.Web.UI.WebControls.TextBox ValueField;
        protected System.Web.UI.WebControls.Button SetCookieButton;
        protected System.Web.UI.WebControls.Label DomainLabel;
        protected System.Web.UI.WebControls.Label PathLabel;
        protected System.Web.UI.WebControls.Button RedirectButton;
    }
}
