//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Egora.Stammportal.HttpReverseProxy.AuthorizationWebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PvpAuthorizerSoap", Namespace="http://www.egora.at/Stammportal/AuthorizationWebService/1.0")]
    public partial class PvpAuthorizer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAuthorizationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PvpAuthorizer() {
            this.Url = global::Egora.Stammportal.HttpReverseProxy.Properties.Settings.Default.Rubicon_Stammportal_HttpReverseProxy_AuthorizationWebService_PvpAuthorizer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAuthorizationCompletedEventHandler GetAuthorizationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.egora.at/Stammportal/AuthorizationWebService/1.0/GetAuthorization", RequestNamespace="http://www.egora.at/Stammportal/AuthorizationWebService/1.0", ResponseNamespace="http://www.egora.at/Stammportal/AuthorizationWebService/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomAuthorization GetAuthorization(string rootUrl, string userId) {
            object[] results = this.Invoke("GetAuthorization", new object[] {
                        rootUrl,
                        userId});
            return ((CustomAuthorization)(results[0]));
        }
        
        /// <remarks/>
        public void GetAuthorizationAsync(string rootUrl, string userId) {
            this.GetAuthorizationAsync(rootUrl, userId, null);
        }
        
        /// <remarks/>
        public void GetAuthorizationAsync(string rootUrl, string userId, object userState) {
            if ((this.GetAuthorizationOperationCompleted == null)) {
                this.GetAuthorizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAuthorizationOperationCompleted);
            }
            this.InvokeAsync("GetAuthorization", new object[] {
                        rootUrl,
                        userId}, this.GetAuthorizationOperationCompleted, userState);
        }
        
        private void OnGetAuthorizationOperationCompleted(object arg) {
            if ((this.GetAuthorizationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAuthorizationCompleted(this, new GetAuthorizationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.egora.at/Stammportal/AuthorizationWebService/1.0")]
    public partial class CustomAuthorization {
        
        private HttpHeader[] httpHeadersField;
        
        private System.Xml.XmlElement soapHeaderXmlFragmentField;
        
        private int timeToLiveField;
        
        /// <remarks/>
        public HttpHeader[] HttpHeaders {
            get {
                return this.httpHeadersField;
            }
            set {
                this.httpHeadersField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement SoapHeaderXmlFragment {
            get {
                return this.soapHeaderXmlFragmentField;
            }
            set {
                this.soapHeaderXmlFragmentField = value;
            }
        }
        
        /// <remarks/>
        public int TimeToLive {
            get {
                return this.timeToLiveField;
            }
            set {
                this.timeToLiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.egora.at/Stammportal/AuthorizationWebService/1.0")]
    public partial class HttpHeader {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetAuthorizationCompletedEventHandler(object sender, GetAuthorizationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAuthorizationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAuthorizationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomAuthorization Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomAuthorization)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591