//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egora.Stammportal.LdapAuthorizationService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Configuration.xml")]
        public string ConfigFile {
            get {
                return ((string)(this["ConfigFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CacheGroupResolution {
            get {
                return ((bool)(this["CacheGroupResolution"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("samAccountName={0}")]
        public string UserFilter {
            get {
                return ((string)(this["UserFilter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(distinguishedName={0}) ")]
        public string GroupFilter {
            get {
                return ((string)(this["GroupFilter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(&(objectCategory=group)(member={0}))")]
        public string ApplicationGroupFilter {
            get {
                return ((string)(this["ApplicationGroupFilter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<pvpToken version=\"{0}\" xmlns=\"http://egov.gv.at/pvp1.xsd\" xmlns:xsi=\"http://www." +
            "w3.org/2001/XMLSchema-instance\">\r\n  <authenticate>\r\n    <participantId>{1}</part" +
            "icipantId>\r\n    {2}\r\n  </authenticate>\r\n  <authorize>\r\n    {3}\r\n  </authorize>\r\n" +
            "</pvpToken>")]
        public string PvpTokenFormat {
            get {
                return ((string)(this["PvpTokenFormat"]));
            }
        }
    }
}
